// <auto-generated />
using System;
using DbContexts.Ad;
using GeoAPI.Geometries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Migrations.AdMigrations
{
    [DbContext(typeof(AdDbContext))]
    partial class AdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Share.Models.Ad.Entities.Ad", b =>
                {
                    b.Property<long>("AdId");

                    b.Property<DateTime?>("ActivatedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<byte>("AdCategoryId");

                    b.Property<string>("AdContent")
                        .IsRequired()
                        .IsUnicode(false);

                    b.Property<byte>("AdDisplayDays");

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("AddressCity")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("AddressCountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("AddressCountryName")
                        .HasMaxLength(75)
                        .IsUnicode(false);

                    b.Property<string>("AddressDistrictOrCounty")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<decimal>("AddressLatitude")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("decimal(20, 10)")
                        .HasDefaultValue(1m);

                    b.Property<IPoint>("AddressLocation")
                        .IsRequired();

                    b.Property<decimal>("AddressLongitude")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("decimal(20, 10)")
                        .HasDefaultValue(1m);

                    b.Property<string>("AddressPartiesMeetingLandmark")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<string>("AddressState")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("AddressZipCode")
                        .HasMaxLength(16)
                        .IsUnicode(false);

                    b.Property<byte>("AttachedAssetsInCloudCount");

                    b.Property<Guid?>("AttachedAssetsInCloudStorageId");

                    b.Property<string>("AttachedAssetsStoredInCloudBaseFolderPath")
                        .HasMaxLength(5000)
                        .IsUnicode(false);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<bool>("IsActivated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<byte>("ItemConditionId");

                    b.Property<double>("ItemCost")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0.0);

                    b.Property<string>("ItemCurrencyCode")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<DateTime?>("PublishedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Tag1")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag10")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag2")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag3")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag4")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag5")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag6")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag7")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag8")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Tag9")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UserIdOrEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<short?>("UserPhoneCountryCode");

                    b.Property<long?>("UserPhoneNumber");

                    b.Property<string>("UserSocialAvatarUrl")
                        .HasMaxLength(5000)
                        .IsUnicode(false);

                    b.Property<string>("UserSocialProviderName")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.HasKey("AdId");

                    b.ToTable("Ad");
                });
#pragma warning restore 612, 618
        }
    }
}
